version: 2.1

parameters:
  rust-version:
    type: string
    default: "1.82.0"

release: &release
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /.*/

jobs:
  build:
    docker:
      - image: cimg/rust:<< pipeline.parameters.rust-version >>
    steps:
      - checkout
      - run:
          name: Cargo fmt
          command: cargo fmt --check
      - run:
          name: Cargo clippy
          command: cargo clippy -- -D warnings -D clippy::todo
      - run:
          name: Cargo test
          command: cargo test

  publish_release:
    docker:
      - image: cimg/rust:<< pipeline.parameters.rust-version >>
    steps:
      - checkout
      - run:
          name: Publish to crates.io
          command: cargo publish -p $CIRCLE_TAG

workflows:
  build:
    jobs:
      - build

  release:
    jobs:
      - build:
          name: Build
          <<: *release

      - publish_release:
          name: Publish to crates.io
          requires:
            - "Build"
          <<: *release
