version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.82.0
    steps:
      - checkout
      - run:
          name: Cargo fmt
          command: cargo fmt --check
      - run:
          name: Cargo clippy
          command: cargo clippy -- -D warnings -D clippy::todo
      - run:
          name: Cargo test
          command: cargo test
